package rules

import com.ling.droolsdemo.entry.Order

rule "zero"
    no-loop true
    lock-on-active true
    salience 1
    when
        $order : Order(amount <= 100)
    then
        $order.setScore(0);
        update($order)
 end

rule "add100"
    no-loop true
    lock-on-active true
    salience 1
    when
        $order : Order(amount > 100 && amount <= 500)
    then
        $order.setScore(100);
        update($order)
 end

rule "add500"
    no-loop true
    lock-on-active true
    salience 1
    when
     $order : Order(amount > 500 && amount <= 1000)
    then
     $order.setScore(500);
     update($order)
end

rule "add1000"
   no-loop true
   lock-on-active true
   salience 1
   when
       $order : Order(amount > 1000)
   then
       $order.setScore(1000);
       update($order)
end