
spring:
  data:
    mongodb:
      uri: mongodb://root:123456@192.168.186.128:27017/ling
      # 副本集配置
#      uri: mongodb://192.168.254.211:28017,192.168.254.211:28018,192.168.254.211:28019/test?connect=replicaSet&slaveOk=true&replicaSet=rs0&readPreference=secondary


#systemLog:
#  destination: file
#  path: "/mongodb/db28017/logs/mongo.log"
#  logAppend: true
#storage:
#  dbPath: "/mongodb/db28017/data"
#  journal:
#    enabled: true
#processManagement:
#  fork: true
#  pidFilePath: "/mongodb/db28017/logs/mongod.pid"
#net:
#  bindIp: 0.0.0.0
#  port: 28017
#replication:
#  replSetName: rs0