spring:
  datasource:
   # driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root


# mybatis\u914D\u7F6E
mybatis:
  configuration:
    map-underscore-to-camel-case: true        #



logging:
  level:
    com:
      ling:
        mapper: warn
